### ISSUE TITLE
Content selectors should be able to easily see which proposals still need votes from the Proposals view

### ISSUE THREAD

**Issue by rahaeli** [osbridge/openconferenceware#105]
I'm doing content voting for OSB for the first time this year (yay, thanks for having me!) and found myself starting out by jumping around in the Proposals view, rather than stepping through each proposal in order, in order to compare multiple similar submissions against each other. (And evaluating a few unrelated proposals here and there when presented with the next proposal after submitting.)

It would be awesome if I could see at a glance from the main Proposals screen which proposals I haven't evaluated yet. That would not only let me catch any ones I accidentally overlooked without having to step through the whole collection of proposals again, but also make it easier to remember where I left off when I come back later without making me have to keep a tab open to my last-evaluated proposal. (I've promised myself I'm going to do this in batches so decision fatigue doesn't kick in.)

**Comment by reidab** [comment]
There should be a little "(Voted)" indication after the title of any talks you've voted on. If this isn't showing up, please let me know. I'll also try to figure out a better way to indicate these or allow for filtering in the future.

**Comment by rahaeli** [comment]
The plot thickens: I wasn't seeing the 'voted' flags in Chrome (version 41.0.2272.104 on Mac OSX 10.8.5) despite repeated refreshes, but checking elsewhere, I did see them in Safari (6.2.3) and Firefox (embarrassingly out of date so I'm not even going to admit a version number).

Trying to narrow it down, I then went back to Chrome and in an incognito window with Adblock Plus as the only extension enabled, and the 'voted' flags did appear.

So, thinking it was an extension conflict, I then went back to the non-incognito window with all my extensions enabled and refreshed again, preparing to start the process of narrowing down which extension it might be ... and the 'voted' flags were there, despite not having been previously.

Really stubborn browser cache, maybe? Although I have Chrome set to minimal cacheing. 

Either way, thank you for arranging the time travel necessary to add this feature before I opened the bug for it. ;) Now that they're actually showing up for me, it's exactly what I would have wanted in the first place. Sorry for the trouble!

**Comment by reidab** [comment]
Ohh. This actually may be server-side caching getting in the way. I'll take a look at that and let you know.

**Comment by rahaeli** [comment]
Oho. That makes sense!

**Comment by reidab** [comment]
I think that may have fixed it.

**Comment by rahaeli** [comment]
Forgot to come back and confirm, but yes, it is fixed and I am now seeing the Voted indicator on the proposals list as soon as I vote. \o/
